spring:
  jpa:
    show-sql: true

springdoc:
  openapi:
    info:
      title: "ğŸ‘µğŸ» Daycan API"
      version: "v1.0.0"
      description: "Daycan API ë¬¸ì„œì…ë‹ˆë‹¤. ..."
  packages-to-scan: com.daycan

  group-configs:
    - group: member
      display-name: ì‚¬ìš©ì API
      paths-to-match: /member/**
    - group: admin
      display-name: ê´€ë¦¬ì API
      paths-to-match: /admin/**

  show-actuator: false
  use-management-port: false
  cache:
    disabled: false

  swagger-ui:
    enabled: true
    path: /api                  # ê¸°ë³¸ì€ /swagger-ui.html ë˜ëŠ” /swagger-ui/index.html
    # í•˜ë‚˜ì˜ ìŠ¤í™ì„ ê°•ì œë¡œ ë°”ë¼ë³´ê²Œ:
    # url: /v3/api-docs.yaml

    urlsPrimaryName: public

    # UI í’ˆì§ˆ/í¸ì˜
    operationsSorter: alpha
    tagsSorter: alpha
    docExpansion: list
    displayRequestDuration: true
    displayOperationId: false
    deepLinking: true
    tryItOutEnabled: true
    filter: true                # true/ë¬¸ìì—´(í•„í„° í‘œí˜„ì‹)
    defaultModelsExpandDepth: 0  # ëª¨ë¸ íŒ¨ë„ ì ‘ê¸°
    defaultModelExpandDepth: 1
    defaultModelRendering: example   # example | model
    persistAuthorization: true       # ë¸Œë¼ìš°ì € ìƒˆë¡œê³ ì¹¨ì—ë„ í† í° ë³´ì¡´
    disable-swagger-default-url: false
